channels:
- conda-forge
dependencies:
- python=3.10.0
- pip<=22.1.2
- pip:
  - mlflow<3,>=2.3
  - cloudpickle==2.2.1
  - numpy==1.22.4
  - scikit-learn==1.1.1
  - scipy==1.8.1
name: mlflow-env
