aliases: []
creation_timestamp: 1683701259898
current_stage: Archived
description: ''
last_updated_timestamp: 1683701399412
name: Gender prediction
run_id: 8cd09d98542942638ff8993acbb900a6
run_link: ''
source: mlflow-artifacts:/385426064880880178/8cd09d98542942638ff8993acbb900a6/artifacts/models
status: READY
status_message: null
user_id: null
version: 2
