aliases: []
creation_timestamp: 1683701095545
current_stage: Production
description: ''
last_updated_timestamp: 1683701177867
name: Gender prediction
run_id: 97f4cf0c706c468391f435db92b4cf1d
run_link: ''
source: mlflow-artifacts:/385426064880880178/97f4cf0c706c468391f435db92b4cf1d/artifacts/models
status: READY
status_message: null
user_id: null
version: 1
